name = "traveling-planet-earth"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
# Public Supabase vars (set real values in Cloudflare Dashboard → Settings → Variables)
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

[[d1_databases]]
# Optional: Falls du später Cloudflare D1 nutzen willst
# binding = "DB"
# database_name = "traveling-planet-earth"
# database_id = ""
